### ISSUE TITLE
Security issue for anonymous users

### ISSUE THREAD

**Issue by DimitriDerthe** [dylandoamaral/pokinder#79]
Hello,

It seems that you have a security breach for anonymous users, where a simple random uuid can be pass as API token to flood your database.

Anonymous token have to be generated on server side, to be signed with your JWT secret key.

Hope this can be helpful.

Regards,
Dimitri

**Comment by dylandoamaral** [comment]
No matter what, you can still connect to the website, retrieve the api key generated by the server and use it afterward no ?

**Comment by DimitriDerthe** [comment]
Of course, but you can add some more protections like requesting a valide xsrf token to generate an anonymous token.

Set a short TTL for anonymous token and add a sleep of 1 or 2 seconds before the response to slowdown the attacker.

You can also add a rate limiting on your API to have a more global protection.

**Comment by dylandoamaral** [comment]
Thank you for your advices !

**Comment by dylandoamaral** [comment]
Should be better after the release, don't hesitate if you find other security issues and thanks for your help !
